version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cp-cyber-app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
