name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build e start da aplicação em container Docker
      - name: Build Docker image
        run: |
          docker build -t my-web-app .

      - name: Start Docker container
        run: |
          docker run -d -p 8080:8080 --name my-web-app my-web-app
          # Espera a aplicação subir
          echo "Waiting for the app to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:8080; then
              echo "App is up!"
              break
            fi
            sleep 2
          done

      # 3. Rodar OWASP ZAP Scan
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://host.docker.internal:8080'
          allow_issue_writing: false
          artifact_name: 'zap-scan-results'
          cmd_options: >
            -r $GITHUB_WORKSPACE/zap-report.html
            -J $GITHUB_WORKSPACE/zap-report.json
            -w $GITHUB_WORKSPACE/zap-report.md
          fail_action: true

      # 4. Upload dos relatórios
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            $GITHUB_WORKSPACE/zap-report.html
            $GITHUB_WORKSPACE/zap-report.json
            $GITHUB_WORKSPACE/zap-report.md

      # 5. Cleanup
      - name: Stop Docker container
        run: docker stop my-web-app && docker rm my-web-app
