name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start application
        run: |
          nohup python app.py &
          sleep 10
      
      - name: Prepare environment for ZAP
        run: |
          sudo chmod -R 777 .
          rm -f zap-report.html report_json.json report_md.md report_html.html

      - name: Run OWASPZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080'
          artifact_name: 'zap-scan-results'
          cmd_options: '-t http://localhost:8080 -r zap-report.html -J report_json.json -w report_md.md'

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
