name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t cp-cyber-app .

      # 2. Run container em background
      - name: Start application container
        run: |
          docker run -d --name cp-cyber-app -p 8080:8080 cp-cyber-app
          # Espera aplicação subir
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "✅ Aplicação rodando!"
              break
            fi
            sleep 3
          done

      # 3. Rodar OWASP ZAP Scan
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080'
          allow_issue_writing: false
          artifact_name: 'zap-scan-results'
          cmd_options: '-r zap-report.html -J zap-report.json -w zap-report.md'
          fail_action: true

      # 4. Upload dos relatórios
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.json
            zap-report.md

      # 5. Stop container
      - name: Stop Docker container
        run: docker stop cp-cyber-app
