name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Ajustar permissões do workspace para evitar erros do ZAP
      - name: Ajustar permissões
        run: sudo chmod -R 777 $GITHUB_WORKSPACE

      # 3️⃣ Subir aplicação via Docker Compose
      - name: Subir aplicação no Docker
        run: |
          docker compose -f docker-compose.yml up -d --build
          echo "Aguardando a aplicação subir..."
          sleep 15  # ajuste se necessário

      # 4️⃣ Rodar OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --network host \
            -v $GITHUB_WORKSPACE:/zap/wrk:rw \
            --user $(id -u):$(id -g) \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t http://host.docker.internal:3001 \
              -r zap-report.html \
              -I

      # 5️⃣ Upload do relatório como artefato
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap-report.html
