name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      app:
        image: python:3.10
        options: >-
          --health-cmd="curl -f http://localhost:8080 || exit 1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5
        ports:
          - 8080:8080
        volumes:
          - ./:/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar dependências e iniciar a aplicação
      - name: Install dependencies and start app
        run: |
          pip install -r requirements.txt
          nohup python app.py &

      # Aguarda o serviço ficar saudável
      - name: Wait for application to be ready
        run: |
          echo "Waiting for app to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:8080; then
              echo "App is up!"
              break
            fi
            sleep 2
          done

      # Rodar OWASP ZAP Scan
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080'
          allow_issue_writing: false
          artifact_name: 'zap-scan-results'
          cmd_options: '-r zap-report.html -J report_json.json -w report_md.md'
          fail_action: true

      # Upload dos relatórios
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: |
            zap-report.html
            report_json.json
            report_md.md
