name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Aguarda a aplicação estar disponível
      - name: Wait for application to be ready
        run: |
          echo "Waiting for app to be ready on http://localhost:8080..."
          for i in {1..30}; do
            if curl -s http://localhost:8080; then
              echo "App is up!"
              break
            fi
            sleep 2
          done

      # 3. Rodar OWASP ZAP Scan
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080'        # URL da aplicação
          allow_issue_writing: false             # não criar issues automaticamente
          artifact_name: 'zap-scan-results'
          cmd_options: >
            -r zap-report.html
            -J zap-report.json
            -w zap-report.md
          fail_action: true                      # falhar se houver alertas críticos

      # 4. Mover relatórios para workspace do GitHub
      - name: Move ZAP reports
        run: |
          mv zap-report.html $GITHUB_WORKSPACE/
          mv zap-report.json $GITHUB_WORKSPACE/
          mv zap-report.md $GITHUB_WORKSPACE/

      # 5. Upload dos relatórios como artefatos
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            $GITHUB_WORKSPACE/zap-report.html
            $GITHUB_WORKSPACE/zap-report.json
            $GITHUB_WORKSPACE/zap-report.md
