name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Subir aplicação e rede com docker-compose
      - name: Subir aplicação com docker-compose
        run: |
          docker-compose up -d --build

      # Esperar container ficar pronto
      - name: Esperar aplicação ficar pronta
        run: |
          echo "Aguardando aplicação subir..."
          until curl -s http://localhost:8080; do
            sleep 2
          done
          echo "Aplicação pronta!"

      # Rodar OWASP ZAP em container conectado à mesma rede
      - name: Rodar OWASP ZAP Baseline Scan
        run: |
          docker run --network host \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:8080 -r zap-report.html -I

      # Upload do relatório como artefato
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap-report.html