name: OWASP ZAP Scan (External App via ngrok)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Define a URL pública do seu túnel ngrok
      # (Substitua pela sua URL atual — deve começar com https://)
      - name: Definir URL da aplicação
        run: echo "APP_URL=https://8cf4d0d384eb.ngrok-free.app" >> $GITHUB_ENV

      # Rodar o OWASP ZAP apontando para a URL pública
      - name: Run OWASP ZAP Baseline Scan
        run: |
          echo "Iniciando scan em: $APP_URL"
          docker run \
            -v $GITHUB_WORKSPACE:/zap/wrk/:rw \
            --user $(id -u):$(id -g) \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t $APP_URL \
              -r zap-report.html \
              -I

      # Upload do relatório como artefato
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap-report.html
