name: OWASP ZAP Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Rodar OWASP ZAP Baseline Scan no endpoint público do ngrok
      - name: Run OWASP ZAP Baseline Scan
        env:
          NGROK_URL: ${{ secrets.NGROK_URL }}
        run: |
          mkdir -p ./zap-reports
          chmod 777 ./zap-reports

          echo "🔍 Iniciando varredura de segurança no endpoint: $NGROK_URL"

          docker run \
            -v $(pwd)/zap-reports:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t $NGROK_URL \
              -r zap-report.html \
              -I

      # Publicar o relatório HTML como artefato
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: ./zap-reports/zap-report.html
