name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start application
        run: |
          nohup python app.py &
          sleep 10  # espera a aplicação iniciar

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080'
          allow_issue_writing: false
          artifact_name: 'zap-scan-results'
          cmd_options: >
            -r $GITHUB_WORKSPACE/zap-report.html
            -J $GITHUB_WORKSPACE/report_json.json
            -w $GITHUB_WORKSPACE/report_md.md
          fail_action: true

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: |
            zap-report.html
            report_json.json
            report_md.md
